model:
  input_dim: null  # Akan diisi secara dinamis berdasarkan vocab
  output_dim: null  # Akan diisi secara dinamis berdasarkan vocab
  embedding_dim: 256
  hidden_dim: 64
  dropout: 0.2

training:
  batch_size: 8
  clip: 1.0
  teacher_forcing_initial: 0.5
  teacher_forcing_final: 0.1
  epochs: 10
  patience: 3
  patience_counter: 0
  checkpoint_path: "../checkpoints/gru_model.pt"
  device: "cpu"

data:
  dataset_path: "../../data/jawa-indo_indoNLP"
  pad_token: "<pad>"
