model:
  input_dim: null  # Akan diisi secara dinamis berdasarkan vocab
  output_dim: null  # Akan diisi secara dinamis berdasarkan vocab
  embedding_dim: 512
  hidden_dim: 1024
  dropout: 0.3

training:
  batch_size: 128
  clip: 1.0
  teacher_forcing_initial: 0.5
  teacher_forcing_final: 0.1
  epochs: 10
  patience: 5
  patience_counter: 0
  checkpoint_path: "checkpoints/gru_model.pt"

data:
  dataset_path: "../../data/jawa-indo_indoNLP"
  pad_token: "<pad>"
